### ISSUE TITLE
Upgrade to v16

### ISSUE THREAD

**Issue by euroblaze** [euroblaze/signatures#3]
## Initial Scope
Upgrade this module to v16.

## New Spec from 16.05.24

I just don't understand the logic of this module! It doesn't make sense.

Consider this implementation..

1. Signatures can be maintained under Settings > Signatures. Main menu in Dashboard isn't necessary. Regular users can reach the signature-table `model=nebiz.signatures` from `My Profile` > `Signatures` (new tab).

2. Under `My Profile` > `Preferences` (tab), it's possible to select a signature and populate `res.users.signature` field. 

3. Model name `nebiz.signatures` carries branding. De-brand it, so any company can use it in v16, v17 and beyond.

4. On Chatters, user can `Select Signature` above the `Send` button. 
    1. `res.user.signature` is selected by default, but user can choose to send message without a signature also (Select `--Send without signature--`).
    2. Offer a list of signatures which are associated with any active company.
    3. So seems like the field `nebiz.signature.active_signature` doesn't make sense, and can be removed.

5. It should be possible to include signatures in automated mailers, ex. {{ a_variable_to_include_signature }}.

6. Internal Messages should not include a signature.

**Comment by VTV24710** [comment]
Hello @euroblaze ,
I try to finish this issue tonight and latest is tomorrow you will have available migrated module
Estimated dd: 15/5
Estimated time: 2hrs

**Comment by euroblaze** [comment]
Approved in anticipation of update on demo16.poweron (demo branch can be created). @VTV24710

**Comment by VTV24710** [comment]
Hello @euroblaze , 

This module is migrated to **V16 (on branch 16.0)**. 
It is also tested on [V16](https://demo16.poweron.software/), you can check and test from your side.
Let me know your feedback after testing, thank you so much !

_Best regards,
Alieh_

**Comment by euroblaze** [comment]
@VTV24710 

Thanks for the upgrade.
Tested it.
Seems like this module needs to be rewritten.

See "New Spec from 16.05.24" above, estimate it and provide a DD please.

Current prioritisation:

> 1. Signatures Module
> 2. ~Schulsachen closure~.
> 3. Folder upload in Odoo15 Nextcloud module.
> 4. chatter_llm_pdfextract. 
> 5. ~chatter_llm_leadextraction (QA problems)~

**Comment by VTV24710** [comment]
Hello @euroblaze ,

I got your point and I will execute the new features.
Give me _5hrs include testing time_. The DD is _today (16/5)_.
Let me know your opinion

Thank you so much !

**Comment by euroblaze** [comment]
@VTV24710 approved, updated.

**Comment by euroblaze** [comment]
Hello @VTV24710 

Test on demo16 was OK.
[Production](https://poweron.software/web) testing was not so successful.

# 1.
Select only PowerOn™ company.

```
  File "/mnt/extra-addons/signatures/controller/discuss.py", line 22, in mail_message_post
    guest.env['ir.attachment'].browse(post_data.get('attachment_ids', []))._check_attachments_access(post_data.get('attachment_tokens'))
AttributeError: 'ir.attachment' object has no attribute '_check_attachments_access'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://poweron.software/web/assets/36340-cf00abb/web.assets_backend.min.js:964:163)
    at XMLHttpRequest.<anonymous> (https://poweron.software/web/assets/36340-cf00abb/web.assets_backend.min.js:971:13)
```

# 2.
1. Default better to have no signature selected.
![image](https://github.com/euroblaze/signatures/assets/7826363/a58ed847-9b4d-447d-9c0c-f789adf5b6ec)

2. If a signature is selected, it should be shown as the selected option. Give label **Signature**.

**Comment by VTV24710** [comment]
Hello @euroblaze ,
All issues are solved, now you can see the new performance on both production and demo 16. However, because there is some issue related to server (can not locate the controller path, same as image path issue), so on demo16, it is not okay for all (we should make our UAT better). You can test on production, I tested and it is good

**Comment by euroblaze** [comment]
Collecting test-feedback here. Plan to implement after 2-3 weeks of production testing. 

---
Signatures related to active companies must all load here..
![image](https://github.com/euroblaze/signatures/assets/7826363/955260a1-0930-48c0-9647-bcc5e857b764)

---
1. It is not necessary for the sender of the message to see the signature. 
    The only interesting message for future reference is the one in the purple box.
    For legal-followups, it's useful to see the whole message that has been sent to recipient in the `model=mail.message` / [example](https://poweron.software/web#id=136914&menu_id=4&cids=4%2C1%2C2%2C3&action=111&model=mail.message&view_type=form).

2. The link-preview below is also creating "clutter" on the chatter.
![image](https://github.com/euroblaze/signatures/assets/7826363/06fe768a-a850-4abf-9c8a-f78fe33e5de0)


Overall, attempt to not pollute the chatter. 
OT: `chatter_llm` pollutes the chatter a lot!
---
The sender email address depends on the signature used! (means we would need a field to store the name and email-address in the model)


cc: @VTV24710

**Comment by euroblaze** [comment]
@VTV24710 
Getting this error each time the CRM form-view is loaded on v16/poweron.software, possibly other form-views with Chatter as well.

```
  File "/mnt/extra-addons/signatures/models/user_signatures.py", line 46, in get_selected_sig
    'x_name': selected_sig.x_name,
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1131, in __get__
    record.ensure_one()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5115, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: user.signatures(1, 2)

The above server error caused the following client error:
RPC_ERROR://poweron.software/web/assets/36718-75d6ed5/web.assets_backend.min.js:964:163)
    at XMLHttpRequest.<anonymous> (https://poweron.software/web/assets/36718-75d6ed5/web.assets_backend.min.js:971:13)
```

**Comment by euroblaze** [comment]
Closing this and moving bugs into individual issues.
@VTV24710 thanks.
