### ISSUE TITLE
Expected singleton: user.signatures(1, 2)

### ISSUE THREAD

**Issue by euroblaze** [euroblaze/signatures#8]
Getting this error each time the CRM form-view is loaded on v16/poweron.software, possibly other form-views with Chatter as well.

```
  File "/mnt/extra-addons/signatures/models/user_signatures.py", line 46, in get_selected_sig
    'x_name': selected_sig.x_name,
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1131, in __get__
    record.ensure_one()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5115, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: user.signatures(1, 2)

The above server error caused the following client error:
RPC_ERROR://poweron.software/web/assets/36718-75d6ed5/web.assets_backend.min.js:964:163)
    at XMLHttpRequest.<anonymous> (https://poweron.software/web/assets/36718-75d6ed5/web.assets_backend.min.js:971:13)
```

_Originally posted by @euroblaze in https://github.com/euroblaze/signatures/issues/3#issuecomment-2157770607_

**Comment by euroblaze** [comment]
@VTV24710 welcoming a fix. Thanks!

**Comment by VTV24710** [comment]
@euroblaze,
Plan to fix this one today ! I will inform you when done!

**Comment by euroblaze** [comment]
@VTV24710 
> Plan to fix this one today ! I will inform you when done!

**Comment by VTV24710** [comment]
Hello @euroblaze ,
Signature V16 was solved and pushed to V16 demo. I tested and it is good, please help me test in your side and leave me your feedback.

Env Test: https://demo16.poweron.software/ 
(admin/admin)

Here is the PR: https://github.com/euroblaze/signatures/pull/9
Thank you so much !
Alieh Vo

**Comment by euroblaze** [comment]
Thanks for the fix!
